services:
    AcmeBundle\DataFixtures\FixturesLoader:
        autowire: true

    Nelmio\Alice\Persister\Doctrine:
        arguments: ['@doctrine.orm.entity_manager']

    Majisti\Testing\Database\FixturesLoader: '@AcmeBundle\DataFixtures\FixturesLoader'
